version: "3"

services:
  am-bigbank-front-office:
    container_name: am-bigbank-front-office
    build:
      context: ./
      dockerfile: Dockerfile.front-office
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_DOCKERIZED_URL}
    volumes:
      - ./apps/am-bigbank-customer/src:/usr/src/app/apps/am-bigbank-customer/src
    networks:
      - net-am-bigbank
    ports:
      - 3000:3000
      - 9229:9229
  am-bigbank-ms-notification:
    container_name: am-bigbank-ms-notification
    build:
      context: ./
      dockerfile: Dockerfile.ms-notify
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_DOCKERIZED_URL}
    volumes:
      - ./apps/bigbank-notification/src:/usr/src/app/apps/bigbank-notification/src
    networks:
      - net-am-bigbank
  am-bigbank-ms-bank-account:
    container_name: am-bigbank-ms-bank-account
    build:
      context: ./
      dockerfile: Dockerfile.ms-bank-account
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_DOCKERIZED_URL}
    volumes:
      - ./apps/bigbank-bank-account/src:/usr/src/app/apps/bigbank-bank-account/src
    networks:
      - net-am-bigbank
  am-bigbank-postgres:
    container_name: am-bigbank-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-demo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-demo}
      PGDATA: /data/postgres
    volumes:
       - am-bigbank-postgres:/data/postgres
    ports:
      - 5452:5432
    networks:
      - net-am-bigbank
    restart: unless-stopped

networks:
  net-am-bigbank:
    driver: bridge

volumes:
    am-bigbank-postgres: